### ISSUE TITLE
적의 공격

### ISSUE THREAD

**Issue by rapa1130** [SUST22Unity/HumanSurvival#11]
### To Do List

- [x] 적 공격력 구현
- [x] 구현한 공격력을 적의 체력, 방어력, 경험치, 넉백 수치 등의 스탯과 통합
- [x] 적과의 접촉/투사체 공격시 플레이어의 방어력을 고려해 플레이어의 체력 감소
- [ ] 플레이어가 피격된 후 아주 짧은 무적시간(=피격 틱) 구현. 틱은 1초당 60번으로 정한 뒤 조절 필요.

자세한 정보는 [적 공격 기능 문서 링크](https://github.com/SUST22Unity/HumanSurvival/wiki/%EC%A0%81-%EC%8B%9C%EC%8A%A4%ED%85%9C#%EC%A0%81%EC%9D%98-%EA%B3%B5%EA%B2%A9-%EA%B8%B0%EB%8A%A5) 참조

**Comment by yhj0329** [comment]
플레이어가 피격된 후 아주 짧은 무적시간(=피격 틱) 구현. 틱은 1초당 60번으로 정한 뒤 조절 필요.
상의 후 구현하지 않기로 함
