### ISSUE TITLE
무기 - 마법 지팡이

### ISSUE THREAD

**Issue by rapa1130** [SUST22Unity/HumanSurvival#13]
### 마법 지팡이
- [x] 레벨 1 수치 적용
- [x] 레벨 업별 수치 적용
- [x] 발사 방향 구현
- [x] 직선 투사 구현
- [x] 이미지 및 궤적 효과 구현

자세한 정보는 [무기 문서- 마법 지팡이](https://github.com/SUST22Unity/HumanSurvival/wiki/Document:-%EB%AC%B4%EA%B8%B0#2-%EB%A7%88%EB%B2%95-%EC%A7%80%ED%8C%A1%EC%9D%B4)

### 진화_신성한 지팡이

- [x] 마법 지팡이 기능 재활용
- [x] 스탯 적용
- [x] 진화 조건 적용

자세한 내용은 [신정한 지팡이 무기 링크](https://github.com/SUST22Unity/HumanSurvival/wiki/%EC%A7%84%ED%99%94-%EB%AC%B4%EA%B8%B0#1-%EC%A7%84%ED%99%94%EC%8B%A0%EC%84%B1%ED%95%9C-%EC%A7%80%ED%8C%A1%EC%9D%B4) 참조

**Comment by seong0929** [comment]
진화할 때의 적용할 스프라이트와 프리팹이 아직 없습니다.

**Comment by rapa1130** [comment]
마법지팡이의 진화형은 동일한 그래픽 리소스를 사용하시면 됩니다.
