### ISSUE TITLE
개임 오버 디테일 정보출력

### ISSUE THREAD

**Issue by rapa1130** [SUST22Unity/HumanSurvival#168]
![Image](https://user-images.githubusercontent.com/121474853/220215879-49848934-21a0-4376-9d80-ac1b38fbd632.png)

### 완성 목록
 1,3,4,5,6,버튼클릭시 메인화면 이동

### 해야될 목록
- [ ] 2
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12
- [x] 13

**Comment by Jeon-YJ1004** [comment]
Weapon에서 필요한 데이터
level
timeToAttack
numberOfDead
level

**Comment by yhj0329** [comment]
초당 피해량 GameManager에 weaponGetTime을 이용해서 하시면 됩니다. 사용법은 GameResult.cs에 주석으로 적어놨습니다.
총 피해량 GameManager에 weaponDamage 사용하시면 됩니다.

**Comment by Jeon-YJ1004** [comment]
장신구 아래 숫자는  레벨(스탯 증가량)인가요?
