### ISSUE TITLE
주인공 스킬/패시브 관리 기능

### ISSUE THREAD

**Issue by rapa1130** [SUST22Unity/HumanSurvival#18]
자세한 정보는 [스킬/패시브 관리 기능](https://github.com/SUST22Unity/HumanSurvival/wiki/%EC%8A%A4%ED%82%AC-%EC%8B%9C%EC%8A%A4%ED%85%9C#%EC%8A%A4%ED%82%AC%ED%8C%A8%EC%8B%9C%EB%B8%8C-%EA%B4%80%EB%A6%AC-%EA%B8%B0%EB%8A%A5) 참조

**Comment by rapa1130** [comment]
- [ ] 스킬/패시브 관리 기능
스킬/패시브를 얻거나 없애거나 레벨이 올라가는 걸 관리
- [ ] 스킬/패시브 레벨업에 따른 변화 반영 기능

**Comment by Jeon-YJ1004** [comment]
스킬/패시브 레벨업에 따른 변화 수치는 정리되있지 않는 건가요?

**Comment by rapa1130** [comment]
해당 수치들은 무기/장신구 To Do List의 각각 무기/장신구를 살펴보시면 있습니다
