### ISSUE TITLE
캐릭터 에셋 추천

### ISSUE THREAD

**Issue by Jeon-YJ1004** [SUST22Unity/HumanSurvival#4]
여러 픽셀 캐릭터가 있는 작가의 스토어입니다. 무료와 유료를 적절히 골라 쓰면 어떨까 싶습니다. 
[에셋 스토어](https://assetstore.unity.com/publishers/31468)

**Comment by seong0929** [comment]
[Seven Thole](https://sventhole.artstation.com/)의 에셋을 적극 활용하는 의견이 기획팀과 일치하며, "[Meeting Log #3](https://github.com/SUST22Unity/HumanSurvival/wiki/Meeting-Log-%233)"에서 받아들이기로 합의를 보았습니다.
