### ISSUE TITLE
스테이지 구현

### ISSUE THREAD

**Issue by rapa1130** [SUST22Unity/HumanSurvival#44]
- [x] 스테이지 생성 구현
- [x] 스테이지에 스킬 발사 적용
- [x] 스테이지에 횃불 자동스폰 적용
- [x] 무한 맵 기능 구현

_실제적인 스테이지 작업이 아님_
_일단 스테이지 공통 사항들만 작업_

자세한 내용은 [스테이지 문서 링크](https://github.com/SUST22Unity/HumanSurvival/wiki/%EB%A7%B5-%EC%8A%A4%ED%85%8C%EC%9D%B4%EC%A7%80-%EC%8B%9C%EC%8A%A4%ED%85%9C#%EC%8A%A4%ED%85%8C%EC%9D%B4%EC%A7%80) 참조

**Comment by seong0929** [comment]
- 스테이지 캐릭터 적용과 레벨 시스템 적용은 스테이지 선택 UI가 있어야 가능(테스트를 위해 한 캐릭터와 레벨 시스템의 완성이 필요)
- 스테이지에 Wave 스폰 기능 적용은 몹 스폰 기능 우선 구현 필요

**Comment by seong0929** [comment]
* [질문 해답](https://github.com/SUST22Unity/HumanSurvival/discussions/104)
* 초기화 또한 스테이지 선택 UI가 존재해야 가능할 것으로 판단
