### ISSUE TITLE
메인화면 씬 여러 개 로드되는 버그

### ISSUE THREAD

**Issue by seong0929** [SUST22Unity/HumanSurvival#78]
메인화면 시작 시 다른 씬이 여러 개 로드되는 버그가 발생되었습니다.
다음 버그 픽스 시 시작할 때 메인화면만 나오도록 수정을 요청합니다.
하고 싶을 때 브랜치 파서하면 됩니다.

**Comment by seong0929** [comment]
- [Fixed multiple scene loading bug](https://github.com/SUST22Unity/HumanSurvival/wiki/Bug-Fix) 이름 바꾸고 close 해주세요

**Comment by yhj0329** [comment]
해결 완료
