### ISSUE TITLE
캐릭터 & 스테이지 선택 UI

### ISSUE THREAD

**Issue by rapa1130** [SUST22Unity/HumanSurvival#83]
## 캐릭터 선택 UI
- [x] 캐릭터 목록 스크롤 구조 구현
- [x] 캐릭터 칸 별 이미지,이름 출력 구현
- [x] 캐릭터 설명창 구현
- [x] 포커싱 및 선택기능 구현
- [x] 최종 캐릭터 결정 및 스테이지로 넘어가기 구현

## 스테이지 선택 UI
- [x] 스테이지 목록 스크롤 구조 구현
- [x] 각 스테이지 칸 별 이미지,이름,설명 출력 구현
- [x] 스테이지 세부 정보 출력 구현

자세한 내용은 [캐릭터 및 스테이지 선택 문서 링크](https://github.com/SUST22Unity/HumanSurvival/wiki/%EB%A7%B5-%EC%8A%A4%ED%85%8C%EC%9D%B4%EC%A7%80-%EC%8B%9C%EC%8A%A4%ED%85%9C#%EC%BA%90%EB%A6%AD%ED%84%B0-%EB%B0%8F-%EC%8A%A4%ED%85%8C%EC%9D%B4%EC%A7%80-%EC%84%A0%ED%83%9D) 참조

**Comment by seong0929** [comment]
스테이지 초기화와  스테이지 최종 결정 및 스테이지 생성 구현은 머지 이후 작업을 해야할 것으로 판정 + 작업량이 클 것으로 예상됨

**Comment by seong0929** [comment]
캐릭터 구매 구현(잠금 해제, 미구매 실루엣, 구매)
상점(재화 시스템)을 완성해야 가능할 것으로 보임
